export type Priority = "urgent" | "high" | "medium" | "low" | "none";

export type WorkspaceId = "personal" | "work" | "projects";

export interface Task {
  id: string;
  title: string;
  notes?: string;
  completed: boolean;
  completedAt?: string; // ISO
  createdAt: string; // ISO
  updatedAt: string; // ISO
  /** ISO timestamp. When `hasTime` is false only the date part is meaningful. */
  dueDate?: string;
  hasTime?: boolean;
  priority: Priority;
  workspace: WorkspaceId;
  tags: string[];
  /** Set when the task was generated by Suru AI (breakdown, assistant, etc.) */
  source?: "ai" | "manual";
}

export type TaskDraft = Pick<Task, "title"> &
  Partial<Pick<Task, "notes" | "dueDate" | "hasTime" | "priority" | "workspace" | "tags" | "source">>;

export type ViewId =
  | "home"
  | "inbox"
  | "today"
  | "upcoming"
  | "completed"
  | `workspace:${WorkspaceId}`;

export type SortKey = "smart" | "due" | "priority" | "created" | "title";
export type StatusFilter = "active" | "completed" | "all";

export interface ListFilters {
  query: string;
  priorities: Priority[];
  tag: string | null;
  sort: SortKey;
  status: StatusFilter;
}

export type ThemePreference = "dark" | "light" | "system";

/* ---------------------------- AI contracts ---------------------------- */

export interface SuggestedTask {
  title: string;
  priority?: Priority;
  dueDate?: string;
  hasTime?: boolean;
  workspace?: WorkspaceId;
  tags?: string[];
  notes?: string;
}

export interface ParsedTask {
  title: string;
  dueDate?: string;
  hasTime?: boolean;
  priority?: Priority;
  workspace?: WorkspaceId;
  tags?: string[];
}

/** Compact projection of a task sent to the assistant (never the whole store). */
export interface TaskContext {
  id: string;
  title: string;
  completed: boolean;
  priority: Priority;
  workspace: WorkspaceId;
  dueDate?: string;
  hasTime?: boolean;
  tags: string[];
  completedAt?: string;
}

export type AiAction = "breakdown" | "enhance" | "parse" | "assistant";

export interface AiRequestMap {
  breakdown: { goal: string; now: string };
  enhance: { title: string; notes?: string };
  parse: { text: string; now: string; timezone: string };
  assistant: {
    message: string;
    now: string;
    timezone: string;
    tasks: TaskContext[];
    history?: { role: "user" | "assistant"; content: string }[];
  };
}

export interface AiResponseMap {
  breakdown: { summary?: string; tasks: SuggestedTask[] };
  enhance: { title: string; notes?: string; reason?: string };
  parse: ParsedTask;
  assistant: {
    reply: string;
    tasks?: SuggestedTask[];
    taskIds?: string[];
  };
}

export type AiMode = "live" | "demo";

export interface AiEnvelope<A extends AiAction> {
  data: AiResponseMap[A];
  mode: AiMode;
  provider?: string;
}
